import { HARVEST_CONFIG } from "../game/gameConfig.js";
import { BLESSINGS } from "../game/blessings.js";

const tutorialAsset = (name) => `assets/ui/tutorial/${name}.jpg`;
const gain = HARVEST_CONFIG.gainUnits;

export const TUTORIAL_STEPS = Object.freeze([
  Object.freeze({
    id: "move-aim",
    navLabel: "Controls",
    title: "Move & Aim",
    lead: "Move Zephyr. Aim the scythe. Do both at once.",
    controls: Object.freeze([
      Object.freeze({ label: "Move", actions: Object.freeze(["moveUp", "moveLeft", "moveDown", "moveRight"]), gamepadLabel: "Left Stick", touchLabel: "Move Stick" }),
      Object.freeze({ label: "Aim", keyboardLabel: "Mouse", gamepadLabel: "Right Stick", touchLabel: "Aim Stick" }),
    ]),
    notes: Object.freeze(["Keep circling. Keep aiming."]),
    image: tutorialAsset("move-aim"),
    imageAlt: "Zephyr facing an enemy inside the purple-grey isometric dungeon.",
  }),
  Object.freeze({
    id: "scythe",
    navLabel: "Scythe",
    title: "Chain the Scythe",
    lead: "Tap Strike for three hits. Hold Reap to charge a full-circle cut.",
    controls: Object.freeze([
      Object.freeze({ label: "Strike / combo", actions: Object.freeze(["attack"]) }),
      Object.freeze({ label: "Charged Reap", actions: Object.freeze(["heavy"]), prefix: "Hold / release" }),
    ]),
    notes: Object.freeze([
      "Third strike = strongest.",
      "Keyboard Reap: hold Q or Middle Mouse, then release.",
      "Perfect Reap: release in the bright window.",
    ]),
    image: tutorialAsset("strike"),
    imageAlt: "Zephyr attacking an enemy with the scythe in the current dungeon view.",
  }),
  Object.freeze({
    id: "dash",
    navLabel: "Dash",
    title: "Dash Through Danger",
    lead: "Dash spends the gold bar. Strike before it ends for a Dash Strike.",
    controls: Object.freeze([
      Object.freeze({ label: "Dash", actions: Object.freeze(["dash"]) }),
      Object.freeze({ label: "Dash Strike", actions: Object.freeze(["attack"]), prefix: "During Dash" }),
    ]),
    notes: Object.freeze([`Perfect Dash: dash as an enemy hit connects (first 120 ms) to evade it and gain +${gain.perfectDash} Harvest.`]),
    image: tutorialAsset("dash"),
    imageAlt: "Zephyr crossing the dungeon in a bright violet dash trail.",
  }),
  Object.freeze({
    id: "harvest",
    navLabel: "Harvest",
    title: "Feed the Harvest",
    lead: "Fight well. Fill all three Harvest segments.",
    facts: Object.freeze([
      Object.freeze({ label: "Close hit", value: `+${gain.closeHit}` }),
      Object.freeze({ label: "Critical", value: `+${gain.critical}` }),
      Object.freeze({ label: "Kill", value: `+${gain.kill}` }),
      Object.freeze({ label: "Perfect Dash / Perfect Reap", value: `+${gain.perfectDash}` }),
    ]),
    notes: Object.freeze([]),
    image: tutorialAsset("hud"),
    imageAlt: "The current Life, Dash, and three-segment Harvest HUD with one segment filled.",
    imageFit: "contain",
  }),
  Object.freeze({
    id: "spend-harvest",
    navLabel: "Techniques",
    title: "Spend the Harvest",
    lead: "One full segment powers one special technique.",
    controls: Object.freeze([
      Object.freeze({ label: "Grave Line", actions: Object.freeze(["attack"]), prefix: "Hold" }),
      Object.freeze({ label: "Reaper's Claim", actions: Object.freeze(["claim"]) }),
    ]),
    notes: Object.freeze(["Claim: attack on the catch for a cleave."]),
    image: tutorialAsset("hud"),
    imageAlt: "The current HUD showing one pale-gold Harvest segment ready to spend.",
    imageFit: "contain",
  }),
  Object.freeze({
    id: "build-ledger",
    navLabel: "Build",
    title: "Read Your Build",
    lead: "Review all five technique Oaths, their effects, and their tradeoffs.",
    controls: Object.freeze([
      Object.freeze({ label: "Build ledger", actions: Object.freeze(["build"]), gamepadLabel: "Back", touchLabel: "Pause → Build" }),
    ]),
    facts: Object.freeze([
      Object.freeze({ label: "Floors 1–5", value: "Swear one Oath per technique" }),
      Object.freeze({ label: "Floors 6–9", value: "Master one owned Oath" }),
    ]),
    notes: Object.freeze(["Combat pauses while the ledger is open.", "Press Build again or Escape to return."]),
    image: tutorialAsset("hud"),
    imageAlt: "The current combat HUD.",
    imageFit: "contain",
  }),
  Object.freeze({
    id: "descend",
    navLabel: "Descent",
    title: "Begin the Descent",
    lead: "Clear the room. Recover at the threshold. Enter the portal.",
    controls: Object.freeze([
      Object.freeze({ label: "Pause", actions: Object.freeze(["pause"]) }),
      Object.freeze({ label: "Interact", actions: Object.freeze(["interact"]) }),
    ]),
    notes: Object.freeze(["Pause → Field Guide to review these lessons anytime."]),
    image: tutorialAsset("move-aim"),
    imageAlt: "Zephyr in the first chamber of the current low-poly dungeon.",
  }),
]);

const glossarySection = (title, entries) => Object.freeze({
  title,
  entries: Object.freeze(entries.map(([term, definition]) => Object.freeze({ term, definition }))),
});

export const GLOSSARY_SECTIONS = Object.freeze([
  glossarySection("The Descent", [
    ["Descent", "A complete attempt through all ten floors."],
    ["Run", "Another name for one Descent, from its seed and difficulty to its ending or defeat."],
    ["Standard Run", "The normal Descent, including its opening, boss confrontation, and ending scenes."],
    ["Speedrun", "A Ruthless Descent that skips story bookends and times play from the first controllable frame to the Witch's defeat."],
    ["Floor", "A group of three combat chambers. Floors 1–9 end with an Oath decision; Floor 10 ends with the Witch."],
    ["Chamber", "One generated combat arena within a floor."],
    ["Room", "The Records and results-screen name for a combat chamber."],
    ["Chamber Threshold", "The safe point after a chamber is cleared. Health recovers here and the run can be suspended."],
    ["Portal", "The exit that opens after a chamber is clear and carries Zephyr onward."],
    ["Seed", "The code that determines a run's generated route, encounters, and Oath order."],
    ["Retry Seed", "Start a new attempt using the same seed."],
    ["Suspend Run", "Save the last stable chamber threshold and return to the title screen."],
    ["Boss", "A major final enemy with a dedicated health bar and multi-stage attack pattern."],
    ["Ending Decision", "The five-second choice after the Witch falls: use Strike or Interact, or let the timer expire."],
    ["Mercy Ending", "The ending recorded when Strike or Interact is used during the final decision."],
    ["Release Ending", "The ending recorded when the final decision timer expires."],
    ["Records", "Statistics and best results saved in this browser, including a separate Speedrun leaderboard."],
  ]),
  glossarySection("Oaths & Build", [
    ["Technique", "One of Zephyr's five upgradable actions: Scythe Combo, Charged Reap, Grave Line, Reaper's Claim, or Dash."],
    ["Technique Oath", "A permanent choice that changes one technique for the rest of the current run."],
    ["Oath Choice", "The three-card decision offered after Floors 1–5, once for each technique."],
    ["Oath Path", "The combat style attached to an Oath: Reaper, Shade, or Grave."],
    ["Reaper", "The gold Oath path, focused on damage, execution, and stagger at a lasting cost."],
    ["Shade", "The blue Oath path, focused on speed, precision, and mobility at a lasting cost."],
    ["Grave", "The violet Oath path, focused on control, survival, and groups at a lasting cost."],
    ["Gain", "The permanent benefit granted by an Oath."],
    ["Tradeoff", "The permanent drawback accepted with an Oath."],
    ["Rank I", "The starting rank of a newly sworn Technique Oath."],
    ["Rank II", "The mastered rank of a Technique Oath, with its Gain improved and its listed Tradeoff retained."],
    ["Mastery", "The Floors 6–9 choice that raises one owned Oath from Rank I to Rank II."],
    ["Current Build", "The pause-time ledger showing all five Technique Oaths, ranks, Gains, and Tradeoffs."],
    ["Active Condition", "A temporary Oath effect that is currently live, shown beneath the combat HUD."],
  ]),
  glossarySection("Combat Rules", [
    ["Life", "Zephyr's health. Reaching zero ends the run."],
    ["Health Damage", "Damage that removes Life from Zephyr or health from an enemy."],
    ["Stagger Damage", "Pressure dealt to an enemy's hidden stagger reserve without directly lowering its health."],
    ["Stagger", "The brief interruption caused when enough Stagger Damage breaks an enemy's reserve."],
    ["Critical Hit", "A stronger scythe hit with distinct impact feedback. Some Oaths can guarantee one."],
    ["Execute", "Instantly defeat an eligible normal enemy below the stated health threshold. Bosses cannot be executed."],
    ["Telegraph", "The visible warning on the ground before an enemy attack becomes dangerous."],
    ["Windup", "The warning time between an attack beginning and its hit becoming active."],
    ["Active Window", "The short part of an attack animation in which it can connect."],
    ["Recovery", "The time after an action before Zephyr or an enemy can act normally again."],
    ["Cooldown", "The recharge time before an action can be used again."],
    ["Timing Window", "A short interval in which an input earns a Perfect action or follow-up."],
    ["Dash Protection", "The brief part of a dash during which incoming attacks cannot damage Zephyr."],
    ["Damage Shield", "Temporary protection that absorbs the stated amount of incoming damage before Life is lost."],
    ["Aegis", "The HUD name for a temporary Damage Shield granted by Pallbearer's Cadence."],
    ["Aim Assist", "A setting that gently biases attacks toward a nearby enemy without moving Zephyr for you."],
    ["Slow", "A temporary reduction to an enemy's movement speed."],
    ["Pull", "Forced movement that draws an enemy toward a strike or recall path."],
    ["Crowd Control", "Effects such as stagger, slow, or pull that limit enemy movement or attacks."],
    ["Whiff", "An attack that hits no enemy."],
  ]),
  glossarySection("Techniques & Harvest", [
    ["Strike", "The basic attack input. Tap it to continue the Scythe Combo or use it during certain follow-up windows."],
    ["Scythe Combo", "Three quick Strike inputs chained together."],
    ["Combo Finisher", "The third and strongest hit of the Scythe Combo."],
    ["Reap", "The control label for Charged Reap."],
    ["Charged Reap", "A heavy circular scythe attack: hold Reap to charge, then release."],
    ["Partial Reap", "A Charged Reap released before reaching full power."],
    ["Full Reap", "A Charged Reap released after reaching full power but outside the Perfect Reap window."],
    ["Perfect Reap", `A Charged Reap released inside its highlighted perfect window. It uses the perfect damage profile and gains +${gain.perfectCharge} Harvest.`],
    ["Perfect Charge", "Another name used for a Perfect Reap when describing its Harvest gain."],
    ["Harvest", "The combat resource used by Grave Line and Reaper's Claim. Skillful hits, criticals, kills, and Perfect actions fill it."],
    ["Close Hit", `A scythe hit made within ${HARVEST_CONFIG.closeHitRange} distance units of an enemy. Each qualifying action earns +${gain.closeHit} Harvest.`],
    ["Harvest Unit", "One point of Harvest. The full meter holds 300 units."],
    ["Harvest Segment", "One block of 100 Harvest units. Grave Line and Reaper's Claim each spend one full segment."],
    ["Grave Line", "Hold Strike with a full Harvest segment to charge a straight piercing attack. One dash is allowed while charging."],
    ["Reaper's Claim", "Spend one Harvest segment to throw the scythe out, recall it, and attempt a catch follow-up."],
    ["Claim", "The short name used by the HUD and controls for Reaper's Claim."],
    ["Outbound", "The first pass of Reaper's Claim as the scythe travels away from Zephyr."],
    ["Recall", "The returning pass of Reaper's Claim as the scythe travels back to Zephyr."],
    ["Catch Window", "The brief moment when the returning Claim can be followed with Strike."],
    ["Catch Cleave", "The empowered follow-up made by pressing Strike during the Claim's Catch Window."],
    ["Dash", "A fast movement burst that spends the gold Dash bar and briefly protects Zephyr."],
    ["Dash Energy", "The gold HUD bar spent by Dash. It refills after the dash cooldown."],
    ["Dash Strike", "A scythe strike started during a dash."],
    ["Perfect Dash", `A dash started as an enemy hit connects—within the base first 120 ms—to evade it and gain +${gain.perfectDash} Harvest. Oaths can change this window.`],
  ]),
  glossarySection("Named Oaths", BLESSINGS.map(({ name, description }) => [name, description])),
  glossarySection("Enemies & Difficulty", [
    ["Grave Thrall", "A close-range enemy that lunges and can chain into a cleave."],
    ["Crypt Reaver", "A mobile enemy that warns with a long lane before dashing through it."],
    ["Ossuary Boneguard", "A durable shield-bearing enemy with close slams and a lane charge."],
    ["Hollow Hexer", "A ranged enemy that fires aimed bolts, fan attacks, and delayed ground circles."],
    ["Veil Wraith", "A mobile enemy that blinks to a flank before sweeping the nearby area."],
    ["Cinder Bombardier", "A ranged area enemy that lobs delayed bombs and follows with a broad burst."],
    ["The Witch", "The Floor 10 boss, using changing attack patterns as the fight progresses."],
    ["Relaxed", "More recovery and fewer overlapping threats, with the complete combat and build system preserved."],
    ["Standard", "The intended balance of readable squad pressure, build choices, and mechanical execution."],
    ["Ruthless", "Tighter telegraphs, coordinated overlaps, and specialist-heavy squads; Speedrun always uses this difficulty."],
  ]),
]);
